### ISSUE TITLE
BInary file?

### ISSUE THREAD

**Issue by M-e-i-k-e-l** [pellepl/arcadehid#1]
Dear Peter,

I've struggled with your arcadehid project to get it compiling with eclipse and ARM plugin, but I have still no success. It seems to be more complicated to solve all paths in the makefile to fit to the system here. 
Very nice job you did! It would be nice to get it run on a 'blue pill' here on my workbench. :-D
Is it possible, that you send me a .hex or an .elf file?

Regards,
   Michael
   emailsiphon@freenet.de

**Comment by pellepl** [comment]
Hi Michael,

I understand you had problems with this, as both projects on which arcadehid depends on have evolved further in life, while arcadehid has not.

Give me a few days and I'll see if I get arcadehid up to working status (can't even build it myself now). From there you should only have to change the gcc path. And, just to be safe, I'll also toss up the build artifacts.

**Comment by pellepl** [comment]
That should do it. Added some info at end of the README.md. Are you planning to use this in an arcade box of some sort?

**Comment by myqel** [comment]
Hi Peter,
I answered via github email reply, but it seems that they didn't arrive you.
So, I copy and paste them into this comment:

email#1 08.04.18:
thanks a lot! I will try your tips tomorrow, respectively this week.
I have left an Odroid C1+ here, it's task for WebDAV has been took over by a Pi3. I planned to realize a RetroPie or at least a C64 emulation with VICE. Big issue there is the (closed SW) GPU driver, up to now I cannot get a hardware rendered full screen.
In a first step it will be just a "flying" setup, no nice arcade housing. We will see.
Theoretically the two Competition Pro joysticks I bought on ebay could be implemented at the GPIOs of the C1, but with an blue pill as "adaptor" - maybe with a keyboard  in an old C64 housing additionally - I'm more flexible to try arcade emulations first on PC, too.
The blue pills here on the table I use for a project with step motors here, it will be a DIY 'clockclock' of http://www.humanssince1982.com/

email#2 09.04.18:
I got it compiling under Windows10 without issues. The path to the arm toolchain was a little bit challenging with spaces and "(x86)" in the default windows path name...
I've flashed it with CoxFlash on a blue pill (128k). No reaction on USB, plugging it in. I guess I have to exchange R10, my Blue Pills are populated with 10k instead of 1,5k.
As my project has an UART debugging port, too, I tried to communicate with putty via UART.
My question: What are the com parameters for UART and virtual com port?
9600 8N1?
115,2k? 

Today's further work:
I changed to a Pi3 now, this savesd a lot of time...
Retropi is running VICE now and works like a charm.

I found the speed for UART2 with 460800 baud in your code, but I want to use the Virtaul Com Device. I went through your config files in root src folder as well as the usb folder, but no clue.
On my Windows10 here the standard Serial-to-USB driver from microsoft is not working, finally it seems to work with the FTDI driver - a least the exclamation mark disappeared. The HID-Devices work with the microsoft HID driver.
So my question: What is the VCD baud rate? Hopefully the FTDI driver didn't fool me, I tried all popular baudrates from 1200 up to 128000 (even 460800, but I guess, this is not supported by windows) with putty.

Have a nice weekend!
Michael

**Comment by myqel** [comment]
Ok, found it in src\usb\usb_prop.c:
115k2,8N1 in the variable 'linecoding' definition.
So now I have to investigate, why it is not working here on the windows machine. All USB-to-Serial drivers, but the FTDI, are giving 'code 10' and do not start. Do you have a hint, which windows driver might work with your hardware ID?
The HID devices for a pair of game pads/Joysticks work so far as pre-configured.
Regards; Michael
